name: Upload assets to release

on:
  release:
    types: [published]

jobs:
  release:
    name: Upload assets to release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set appVersion
        uses: bhowell2/github-substring-action@v1
        id: appVersion
        with:
          value: ${{github.ref}}
          index_of_str: "refs/tags/v"

      - run: echo "Version = ${{steps.appVersion.outputs.substring}}"

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Package app
        run: ./gradlew shadowJar --no-daemon

      - name: Package preprocessor
        run: make scriptPkg

      - name: Upload jar to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          tag: ${{ github.ref }}
          file: build/libs/pharmcat-${{steps.appVersion.outputs.substring}}-all.jar
          overwrite: true

      - name: Upload preprocessor to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          tag: ${{ github.ref }}
          file: build/preprocessor.tar.gz
          asset_name: pharmcat-preprocessor-${{steps.appVersion.outputs.substring}}.tar.gz
          overwrite: true

      - name: Upload positions.vcf to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          tag: ${{ github.ref }}
          file: pharmcat_positions.vcf
          asset_name: pharmcat_positions_${{steps.appVersion.outputs.substring}}.vcf
          overwrite: true

      - name: Upload positions.vcf.bgz to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          tag: ${{ github.ref }}
          file: pharmcat_positions.vcf.bgz
          asset_name: pharmcat_positions_${{steps.appVersion.outputs.substring}}.vcf.bgz
          overwrite: true

      - name: Upload positions.vcf.bgz.csi to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          tag: ${{ github.ref }}
          file: pharmcat_positions.vcf.bgz.csi
          asset_name: pharmcat_positions_${{steps.appVersion.outputs.substring}}.vcf.bgz.csi
          overwrite: true

      - name: Upload positions.uniallelic.vcf.bgz to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          tag: ${{ github.ref }}
          file: pharmcat_positions.uniallelic.vcf.bgz
          asset_name: pharmcat_positions_${{steps.appVersion.outputs.substring}}.uniallelic.vcf.bgz
          overwrite: true

      - name: Upload positions.uniallelic.vcf.bgz.csi to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          tag: ${{ github.ref }}
          file: pharmcat_positions.uniallelic.vcf.bgz.csi
          asset_name: pharmcat_positions_${{steps.appVersion.outputs.substring}}.uniallelic.vcf.bgz.csi
          overwrite: true


      - name: Send Slack notification on failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: dev
          status: FAILED
          color: danger
